/*
===============================================================================
Database Exploration (Aggregations and Groupings)
===============================================================================
Purpose:
    - To analyze customer distribution across countries and demographic segments.
    - To evaluate product distributions, average costs, and total revenue by category.
    - To identify high-value customers based on individual revenue generation.
    - To measure country-level revenue performance and market share contributions.

Tables Used:
    - gold.dim_customers
    - gold.dim_products
    - gold.fact_sales
===============================================================================
*/

-- Find total customers by countries 
SELECT 
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Find the total customer by gender 
SELECT 
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Find the total product by category 
SELECT 
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- Average cost in each category
SELECT 
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;


-- Total revenue generated by each category 
SELECT 
    p.category,
    SUM(s.sales_amount) AS revenue_by_category
FROM gold.dim_products p
INNER JOIN gold.fact_sales s
    ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY revenue_by_category DESC;


-- Total revenue generated by each customer
SELECT 
    c.customer_key,
    c.first_name + ' ' + c.last_name AS customer_name,
    SUM(s.sales_amount)              AS total_sales_by_customer
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
    ON s.customer_key = c.customer_key
GROUP BY 
    c.customer_key,
    c.first_name + ' ' + c.last_name
ORDER BY total_sales_by_customer DESC;


-- Distribution of sales across countries percent
SELECT
    country,
    sales_per_country,
    ROUND(CUME_DIST() OVER (ORDER BY sales_per_country) * 100, 3) AS percent_contribution 
FROM (
    SELECT 
        c.country,
        SUM(s.sales_amount) AS sales_per_country
    FROM gold.fact_sales s
    LEFT JOIN gold.dim_customers c
        ON s.customer_key = c.customer_key
    GROUP BY c.country
) t;


-- Distribution of sales across countries  
SELECT 
    c.country,
    SUM(s.sales_amount) AS sales_per_country
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
    ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY sales_per_country DESC;
